version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: "@types/luxon"
    versions:
    - 1.26.3
    - 1.26.4
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@ionic/vue-router"
    versions:
    - 5.6.2
    - 5.6.3
    - 5.6.4
  - dependency-name: "@ionic/vue"
    versions:
    - 5.6.2
    - 5.6.3
    - 5.6.4
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: vue-router
    versions:
    - 4.0.6
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.11
  - dependency-name: mapbox-gl
    versions:
    - 2.2.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.8.0
  - dependency-name: ionicons
    versions:
    - 5.5.1
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.12
  - dependency-name: sass-loader
    versions:
    - 11.0.1
  - dependency-name: "@capacitor/core"
    versions:
    - 2.4.6
  - dependency-name: "@capacitor/cli"
    versions:
    - 2.4.6
